# # Stage 1: Build the application
# FROM mcr.microsoft.com/dotnet/sdk:9.0-preview AS build
# WORKDIR /src
# COPY TodoApi.csproj .
# RUN dotnet restore

# COPY . .
# RUN dotnet publish -c Release -o /app/publish

# # Stage 2: Run the application
# FROM mcr.microsoft.com/dotnet/aspnet:9.0-preview
# WORKDIR /app
# COPY --from=build /app/publish .
# ENTRYPOINT ["dotnet", "TodoApi.dll"]

# https://hub.docker.com/_/microsoft-dotnet
# FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
# WORKDIR /src

# # copy csproj and restore as distinct layers
# COPY *.sln .
# COPY *.csproj ./
# RUN dotnet restore

# # copy everything else and build app
# COPY . ./
# WORKDIR /app
# RUN dotnet publish -c release -o /app --no-restore

# # final stage/image
# FROM mcr.microsoft.com/dotnet/aspnet:9.0
# WORKDIR /app
# COPY --from=build /app ./
# ENTRYPOINT ["dotnet", "TodoApi.dll"]

FROM mcr.microsoft.com/dotnet/sdk:9.0@sha256:3fcf6f1e809c0553f9feb222369f58749af314af6f063f389cbd2f913b4ad556 AS build
WORKDIR /App

# Copy everything
COPY . ./
# Restore as distinct layers
RUN dotnet restore
# Build and publish a release
RUN dotnet publish -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:9.0@sha256:b4bea3a52a0a77317fa93c5bbdb076623f81e3e2f201078d89914da71318b5d8
WORKDIR /App
COPY --from=build /App/out .
# Copy the certificate from your host into the container
COPY aspnetapp.pfx .
ENTRYPOINT ["dotnet", "TodoApi.dll"]