using System;
using System.ComponentModel.DataAnnotations;
using TodoApi.Models;


namespace TodoApi.Models
{
    public class Vehicle
    {
        // Guid === UUID
        public Guid id { get; set; }
        public required string make { get; set; }
        public required string model { get; set; }
        public int year { get; set; }
    }

    // DTO for creating a new Vehicle
    // Excludes the 'id' property since it will be generated by the server
    public class VehicleCreateDto
    {
        public required string make { get; set; }
        public required string model { get; set; }
        public int year { get; set; }
    }
}